### ISSUE TITLE
How to get this to start?

### ISSUE THREAD

**Issue by Talcon** [Wyvryn/HummingbirdExport#4]
In the readme file it says this: 

To run locally, populate the data in `hummingbirdexport/config.py.template` and save it as `hummingbirdexport/config.py`.

I don't know know what that means... is there an option on Hummingbird website to make this start working? How do I start the export of my Hummingbird library?

I followed the link at http://hummingbird.illyasviel.moe/ and it's just a blank white screen

**Comment by Wyvryn** [comment]
Hey, thanks for commenting. To get the exporter running locally you need to checkout this repo, and, from the root directory, run `make env` to build the virtualenv, `source ./env/bin/activate` to activate the virtualenv, and finally `python manage.py runserver`.

As far as config.py.template goes, you'd need to rename that file config.py and put real data in it.

I switched hosts a little while back so I kind of forgot about this project, but it's currently up and running @ [http://hummingbird.illyasviel.moe](http://hummingbird.illyasviel.moe)
